### ISSUE TITLE
我看插件只判断了cart和buy两个域名，但现在的好像不到时间不能加购

### ISSUE THREAD

**Issue by tmsdy** [cehui0303/Tmall_Tickets#1]
现在的抢购链接是 https://chaoshi.detail.tmall.com/item.htm?id=20739895092&toSite=main
没法加购呢。。

**Comment by cehui0303** [comment]
> 现在的抢购链接是 https://chaoshi.detail.tmall.com/item.htm?id=20739895092&toSite=main
> 没法加购呢。。

手机端可以加入购物车

**Comment by hyx616710866** [comment]
请问加购之后，是不是还要等到开抢时间才能买？那部等于没什么用吗？

**Comment by cehui0303** [comment]
> 请问加购之后，是不是还要等到开抢时间才能买？那部等于没什么用吗？

不需要，看代码的逻辑也可以了解。网页不关就可以，但长时间可能会导致登录账号的session过时。
