### ISSUE TITLE
请问是否在浏览器安装此插件后便会自动运行该插件？

### ISSUE THREAD

**Issue by MrWuPengfei** [cehui0303/Tmall_Tickets#2]
我在浏览器安装插件后，点击该插件并不像其他插件一样会有反应，不知道是否已经在自动运行了？

**Comment by cehui0303** [comment]
> 我在浏览器安装插件后，点击该插件并不像其他插件一样会有反应，不知道是否已经在自动运行了？

可以f12看到console有日志输出，我考虑后面加一个显示或弹出一个对话框告知用户在运行

**Comment by MrWuPengfei** [comment]
> > 我在浏览器安装插件后，点击该插件并不像其他插件一样会有反应，不知道是否已经在自动运行了？
> 
> 可以f12看到console有日志输出，我考虑后面加一个显示或弹出一个对话框告知用户在运行

谢谢，看到有输出，是在运行着。加上状态显示确实要好些。
